.separator ","
--Translations
CREATE TABLE "i18n" (
  "_id" INTEGER PRIMARY KEY NOT NULL ,
  "en" TEXT NOT NULL ,
  "pl" TEXT NOT NULL 
);
CREATE INDEX IDX_i18n__id ON i18n ("_id" ASC);
CREATE UNIQUE INDEX IDX_i18n_en ON i18n ("en" ASC);
.import "i18n.csv" i18n

--Tags
CREATE TABLE "TAGS" (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT ,
  "NAME" TEXT NOT NULL 
);
CREATE UNIQUE INDEX IDX_TAGS__id ON TAGS ("_id" ASC);
CREATE UNIQUE INDEX IDX_TAGS_NAME ON TAGS ("NAME" ASC);
.import "tags.csv" TAGS

--Ingredient templates
CREATE TABLE "INGREDIENTS_TEMPLATE" (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT ,
  "NAME" TEXT NOT NULL ,
  "IMAGE_URI" TEXT ,
  "CREATION_DATE" INTEGER NOT NULL ,
  "AMOUNT_TYPE" INTEGER NOT NULL ,
  "ENERGY_DENSITY_AMOUNT" TEXT NOT NULL 
);
CREATE UNIQUE INDEX IDX_INGREDIENTS_TEMPLATE__id ON INGREDIENTS_TEMPLATE ("_id" ASC);
CREATE INDEX IDX_INGREDIENTS_TEMPLATE_NAME ON INGREDIENTS_TEMPLATE ("NAME" ASC);
.import "ingredients_template.csv" INGREDIENTS_TEMPLATE

-- Relationship one tag to many ingredient template
CREATE TABLE "INGREDIENT_TAG_JOINTS" (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT ,
  "TAG_ID" INTEGER NOT NULL ,
  "INGREDIENT_TYPE_ID" INTEGER NOT NULL 
);
CREATE UNIQUE INDEX IDX_INGREDIENT_TAG_JOINTS__id ON INGREDIENT_TAG_JOINTS ("_id" ASC);
CREATE INDEX IDX_INGREDIENT_TAG_JOINTS_TAG_ID ON INGREDIENT_TAG_JOINTS ("TAG_ID" ASC);
CREATE INDEX IDX_INGREDIENT_TAG_JOINTS_INGREDIENT_TYPE_ID ON INGREDIENT_TAG_JOINTS ("INGREDIENT_TYPE_ID" ASC);
.import "ingredient_tags.csv" INGREDIENT_TAG_JOINTS

--Meals
CREATE TABLE "MEALS" (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT ,
  "NAME" TEXT ,
  "IMAGE_URI" TEXT ,
  "CREATION_DATE" INTEGER NOT NULL 
);
CREATE UNIQUE INDEX IDX_MEALS__id ON MEALS ("_id" ASC);
CREATE INDEX IDX_MEALS_NAME ON MEALS ("NAME" ASC);
CREATE INDEX IDX_MEALS_CREATION_DATE ON MEALS ("CREATION_DATE" ASC);

--Body weight
CREATE TABLE "WEIGTH" (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT ,
  "MEASUREMENT_DATE" INTEGER NOT NULL ,
  "WEIGHT" REAL NOT NULL
);
CREATE UNIQUE INDEX IDX_WEIGTH__id ON WEIGTH ("_id" ASC);
CREATE UNIQUE INDEX IDX_WEIGTH_MEASUREMENT_DATE ON WEIGTH ("MEASUREMENT_DATE" ASC);

-- Ingredient
CREATE TABLE "INGREDIENTS" (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT ,
  "AMOUNT" TEXT NOT NULL ,
  "PART_OF_MEAL_ID" INTEGER NOT NULL ,
  "INGREDIENT_TYPE_ID" INTEGER NOT NULL 
);
CREATE UNIQUE INDEX IDX_INGREDIENTS__id ON INGREDIENTS ("_id" ASC);


