CREATE TABLE "i18n" (
  "_id" INTEGER PRIMARY KEY NOT NULL ,
  "en" TEXT NOT NULL ,
  "pl" TEXT NOT NULL
);
--  Add Indexes
CREATE INDEX IDX_i18n__id ON i18n ("_id" ASC);
CREATE UNIQUE INDEX IDX_i18n_en ON i18n ("en" ASC);

CREATE TABLE "TAGS_NEW" (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT ,
  "NAME" TEXT NOT NULL ,
  "CREATION_SOURCE" INTEGER NOT NULL
);
INSERT INTO "TAGS_NEW"  ("_id", "NAME", "CREATION_SOURCE")
  SELECT "_id", "NAME", "1" FROM "TAGS";
DROP TABLE "TAGS";
ALTER TABLE "TAGS_NEW" RENAME TO "TAGS";

CREATE UNIQUE INDEX IDX_TAGS__id ON TAGS ("_id" ASC);
CREATE UNIQUE INDEX IDX_TAGS_NAME ON TAGS ("NAME" ASC);
CREATE INDEX IDX_TAGS_CREATION_DATE ON TAGS  ("CREATION_SOURCE" ASC);

CREATE TABLE "INGREDIENTS_TEMPLATE_NEW" (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT ,
  "NAME" TEXT NOT NULL ,
  "IMAGE_URI" TEXT ,
  "CREATION_SOURCE" INTEGER NOT NULL ,
  "AMOUNT_TYPE" INTEGER NOT NULL ,
  "ENERGY_DENSITY_AMOUNT" TEXT NOT NULL
);
INSERT INTO "INGREDIENTS_TEMPLATE_NEW"  (
  "_id", "NAME", "IMAGE_URI", "CREATION_SOURCE", "AMOUNT_TYPE", "ENERGY_DENSITY_AMOUNT")
  SELECT
  "_id", "NAME", "IMAGE_URI", "1", "AMOUNT_TYPE", "ENERGY_DENSITY_AMOUNT"
  FROM "INGREDIENTS_TEMPLATE";
DROP TABLE "INGREDIENTS_TEMPLATE";
ALTER TABLE "INGREDIENTS_TEMPLATE_NEW" RENAME TO "INGREDIENTS_TEMPLATE";

CREATE UNIQUE INDEX IDX_INGREDIENTS_TEMPLATE__id ON INGREDIENTS_TEMPLATE ("_id" ASC);
CREATE INDEX IDX_INGREDIENTS_TEMPLATE_NAME ON INGREDIENTS_TEMPLATE ("NAME" ASC);
CREATE INDEX IDX_INGREDIENTS_TEMPLATE_CREATION_SOURCE ON INGREDIENTS_TEMPLATE ("CREATION_SOURCE" ASC);
