CREATE TABLE "WEIGTH" (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT ,
  "MEASUREMENT_DATE" INTEGER NOT NULL ,
  "WEIGHT" REAL NOT NULL
);
-- Add Indexes
CREATE UNIQUE INDEX IDX_WEIGTH__id ON WEIGTH ("_id" ASC);
CREATE UNIQUE INDEX IDX_WEIGTH_MEASUREMENT_DATE ON WEIGTH ("MEASUREMENT_DATE" ASC);
CREATE INDEX IF NOT EXISTS IDX_MEALS_CREATION_DATE ON MEALS ("CREATION_DATE" ASC);