package com.github.st1hy.countthemcalories.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.github.st1hy.countthemcalories.database.IngredientTemplate;
import com.github.st1hy.countthemcalories.database.Ingredient;
import com.github.st1hy.countthemcalories.database.Meal;
import com.github.st1hy.countthemcalories.database.Day;
import com.github.st1hy.countthemcalories.database.Tag;
import com.github.st1hy.countthemcalories.database.JointIngredientTag;

import com.github.st1hy.countthemcalories.database.IngredientTemplateDao;
import com.github.st1hy.countthemcalories.database.IngredientDao;
import com.github.st1hy.countthemcalories.database.MealDao;
import com.github.st1hy.countthemcalories.database.DayDao;
import com.github.st1hy.countthemcalories.database.TagDao;
import com.github.st1hy.countthemcalories.database.JointIngredientTagDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ingredientTemplateDaoConfig;
    private final DaoConfig ingredientDaoConfig;
    private final DaoConfig mealDaoConfig;
    private final DaoConfig dayDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig jointIngredientTagDaoConfig;

    private final IngredientTemplateDao ingredientTemplateDao;
    private final IngredientDao ingredientDao;
    private final MealDao mealDao;
    private final DayDao dayDao;
    private final TagDao tagDao;
    private final JointIngredientTagDao jointIngredientTagDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ingredientTemplateDaoConfig = daoConfigMap.get(IngredientTemplateDao.class).clone();
        ingredientTemplateDaoConfig.initIdentityScope(type);

        ingredientDaoConfig = daoConfigMap.get(IngredientDao.class).clone();
        ingredientDaoConfig.initIdentityScope(type);

        mealDaoConfig = daoConfigMap.get(MealDao.class).clone();
        mealDaoConfig.initIdentityScope(type);

        dayDaoConfig = daoConfigMap.get(DayDao.class).clone();
        dayDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        jointIngredientTagDaoConfig = daoConfigMap.get(JointIngredientTagDao.class).clone();
        jointIngredientTagDaoConfig.initIdentityScope(type);

        ingredientTemplateDao = new IngredientTemplateDao(ingredientTemplateDaoConfig, this);
        ingredientDao = new IngredientDao(ingredientDaoConfig, this);
        mealDao = new MealDao(mealDaoConfig, this);
        dayDao = new DayDao(dayDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        jointIngredientTagDao = new JointIngredientTagDao(jointIngredientTagDaoConfig, this);

        registerDao(IngredientTemplate.class, ingredientTemplateDao);
        registerDao(Ingredient.class, ingredientDao);
        registerDao(Meal.class, mealDao);
        registerDao(Day.class, dayDao);
        registerDao(Tag.class, tagDao);
        registerDao(JointIngredientTag.class, jointIngredientTagDao);
    }
    
    public void clear() {
        ingredientTemplateDaoConfig.getIdentityScope().clear();
        ingredientDaoConfig.getIdentityScope().clear();
        mealDaoConfig.getIdentityScope().clear();
        dayDaoConfig.getIdentityScope().clear();
        tagDaoConfig.getIdentityScope().clear();
        jointIngredientTagDaoConfig.getIdentityScope().clear();
    }

    public IngredientTemplateDao getIngredientTemplateDao() {
        return ingredientTemplateDao;
    }

    public IngredientDao getIngredientDao() {
        return ingredientDao;
    }

    public MealDao getMealDao() {
        return mealDao;
    }

    public DayDao getDayDao() {
        return dayDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public JointIngredientTagDao getJointIngredientTagDao() {
        return jointIngredientTagDao;
    }

}
