package com.github.st1hy.countthemcalories.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.github.st1hy.countthemcalories.database.IngredientTemplate;
import com.github.st1hy.countthemcalories.database.Ingredient;
import com.github.st1hy.countthemcalories.database.Meal;
import com.github.st1hy.countthemcalories.database.Tag;
import com.github.st1hy.countthemcalories.database.JointIngredientTag;

import com.github.st1hy.countthemcalories.database.IngredientTemplateDao;
import com.github.st1hy.countthemcalories.database.IngredientDao;
import com.github.st1hy.countthemcalories.database.MealDao;
import com.github.st1hy.countthemcalories.database.TagDao;
import com.github.st1hy.countthemcalories.database.JointIngredientTagDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ingredientTemplateDaoConfig;
    private final DaoConfig ingredientDaoConfig;
    private final DaoConfig mealDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig jointIngredientTagDaoConfig;

    private final IngredientTemplateDao ingredientTemplateDao;
    private final IngredientDao ingredientDao;
    private final MealDao mealDao;
    private final TagDao tagDao;
    private final JointIngredientTagDao jointIngredientTagDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ingredientTemplateDaoConfig = daoConfigMap.get(IngredientTemplateDao.class).clone();
        ingredientTemplateDaoConfig.initIdentityScope(type);

        ingredientDaoConfig = daoConfigMap.get(IngredientDao.class).clone();
        ingredientDaoConfig.initIdentityScope(type);

        mealDaoConfig = daoConfigMap.get(MealDao.class).clone();
        mealDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        jointIngredientTagDaoConfig = daoConfigMap.get(JointIngredientTagDao.class).clone();
        jointIngredientTagDaoConfig.initIdentityScope(type);

        ingredientTemplateDao = new IngredientTemplateDao(ingredientTemplateDaoConfig, this);
        ingredientDao = new IngredientDao(ingredientDaoConfig, this);
        mealDao = new MealDao(mealDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        jointIngredientTagDao = new JointIngredientTagDao(jointIngredientTagDaoConfig, this);

        registerDao(IngredientTemplate.class, ingredientTemplateDao);
        registerDao(Ingredient.class, ingredientDao);
        registerDao(Meal.class, mealDao);
        registerDao(Tag.class, tagDao);
        registerDao(JointIngredientTag.class, jointIngredientTagDao);
    }
    
    public void clear() {
        ingredientTemplateDaoConfig.clearIdentityScope();
        ingredientDaoConfig.clearIdentityScope();
        mealDaoConfig.clearIdentityScope();
        tagDaoConfig.clearIdentityScope();
        jointIngredientTagDaoConfig.clearIdentityScope();
    }

    public IngredientTemplateDao getIngredientTemplateDao() {
        return ingredientTemplateDao;
    }

    public IngredientDao getIngredientDao() {
        return ingredientDao;
    }

    public MealDao getMealDao() {
        return mealDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public JointIngredientTagDao getJointIngredientTagDao() {
        return jointIngredientTagDao;
    }

}
