package com.github.st1hy.countthemcalories.database;

import java.util.List;
import com.github.st1hy.countthemcalories.database.DaoSession;
import de.greenrobot.dao.DaoException;

import android.net.Uri;
import com.github.st1hy.countthemcalories.database.unit.EnergyDensity;
import org.joda.time.DateTime;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INGREDIENTS_TEMPLATE".
 */
public class IngredientTemplate {

    private Long id;
    /** Not-null value. */
    private String name;
    private Uri imageUri;
    private DateTime creationDate;
    /** Not-null value. */
    private EnergyDensity energyDensity;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient IngredientTemplateDao myDao;

    private List<Ingredient> childIngredients;
    private List<JointIngredientTag> tags;

    public IngredientTemplate() {
    }

    public IngredientTemplate(Long id) {
        this.id = id;
    }

    public IngredientTemplate(Long id, String name, Uri imageUri, DateTime creationDate, EnergyDensity energyDensity) {
        this.id = id;
        this.name = name;
        this.imageUri = imageUri;
        this.creationDate = creationDate;
        this.energyDensity = energyDensity;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getIngredientTemplateDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Uri getImageUri() {
        return imageUri;
    }

    public void setImageUri(Uri imageUri) {
        this.imageUri = imageUri;
    }

    public DateTime getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(DateTime creationDate) {
        this.creationDate = creationDate;
    }

    /** Not-null value. */
    public EnergyDensity getEnergyDensity() {
        return energyDensity;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEnergyDensity(EnergyDensity energyDensity) {
        this.energyDensity = energyDensity;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Ingredient> getChildIngredients() {
        if (childIngredients == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            IngredientDao targetDao = daoSession.getIngredientDao();
            List<Ingredient> childIngredientsNew = targetDao._queryIngredientTemplate_ChildIngredients(id);
            synchronized (this) {
                if(childIngredients == null) {
                    childIngredients = childIngredientsNew;
                }
            }
        }
        return childIngredients;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetChildIngredients() {
        childIngredients = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<JointIngredientTag> getTags() {
        if (tags == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            JointIngredientTagDao targetDao = daoSession.getJointIngredientTagDao();
            List<JointIngredientTag> tagsNew = targetDao._queryIngredientTemplate_Tags(id);
            synchronized (this) {
                if(tags == null) {
                    tags = tagsNew;
                }
            }
        }
        return tags;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetTags() {
        tags = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
