package com.github.st1hy.countthemcalories.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.github.st1hy.countthemcalories.database.property.BigDecimalPropertyConverter;
import java.math.BigDecimal;

import com.github.st1hy.countthemcalories.database.Ingredient;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INGREDIENTS".
*/
public class IngredientDao extends AbstractDao<Ingredient, Long> {

    public static final String TABLENAME = "INGREDIENTS";

    /**
     * Properties of entity Ingredient.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Amount = new Property(1, String.class, "amount", false, "AMOUNT");
        public final static Property PartOfMealId = new Property(2, Long.class, "partOfMealId", false, "PART_OF_MEAL_ID");
        public final static Property IngredientTypeId = new Property(3, Long.class, "ingredientTypeId", false, "INGREDIENT_TYPE_ID");
    };

    private DaoSession daoSession;

    private final BigDecimalPropertyConverter amountConverter = new BigDecimalPropertyConverter();
    private Query<Ingredient> meal_IngredientsQuery;
    private Query<Ingredient> ingredientTemplate_ChildIngredientsQuery;

    public IngredientDao(DaoConfig config) {
        super(config);
    }
    
    public IngredientDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INGREDIENTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"AMOUNT\" TEXT NOT NULL ," + // 1: amount
                "\"PART_OF_MEAL_ID\" INTEGER," + // 2: partOfMealId
                "\"INGREDIENT_TYPE_ID\" INTEGER);"); // 3: ingredientTypeId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_INGREDIENTS__id ON INGREDIENTS" +
                " (\"_id\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INGREDIENTS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Ingredient entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, amountConverter.convertToDatabaseValue(entity.getAmount()));
 
        Long partOfMealId = entity.getPartOfMealId();
        if (partOfMealId != null) {
            stmt.bindLong(3, partOfMealId);
        }
 
        Long ingredientTypeId = entity.getIngredientTypeId();
        if (ingredientTypeId != null) {
            stmt.bindLong(4, ingredientTypeId);
        }
    }

    @Override
    protected void attachEntity(Ingredient entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Ingredient readEntity(Cursor cursor, int offset) {
        Ingredient entity = new Ingredient( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            amountConverter.convertToEntityProperty(cursor.getString(offset + 1)), // amount
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // partOfMealId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // ingredientTypeId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Ingredient entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAmount(amountConverter.convertToEntityProperty(cursor.getString(offset + 1)));
        entity.setPartOfMealId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIngredientTypeId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Ingredient entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Ingredient entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "ingredients" to-many relationship of Meal. */
    public List<Ingredient> _queryMeal_Ingredients(Long partOfMealId) {
        synchronized (this) {
            if (meal_IngredientsQuery == null) {
                QueryBuilder<Ingredient> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PartOfMealId.eq(null));
                meal_IngredientsQuery = queryBuilder.build();
            }
        }
        Query<Ingredient> query = meal_IngredientsQuery.forCurrentThread();
        query.setParameter(0, partOfMealId);
        return query.list();
    }

    /** Internal query to resolve the "childIngredients" to-many relationship of IngredientTemplate. */
    public List<Ingredient> _queryIngredientTemplate_ChildIngredients(Long ingredientTypeId) {
        synchronized (this) {
            if (ingredientTemplate_ChildIngredientsQuery == null) {
                QueryBuilder<Ingredient> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IngredientTypeId.eq(null));
                ingredientTemplate_ChildIngredientsQuery = queryBuilder.build();
            }
        }
        Query<Ingredient> query = ingredientTemplate_ChildIngredientsQuery.forCurrentThread();
        query.setParameter(0, ingredientTypeId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMealDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getIngredientTemplateDao().getAllColumns());
            builder.append(" FROM INGREDIENTS T");
            builder.append(" LEFT JOIN MEALS T0 ON T.\"PART_OF_MEAL_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN INGREDIENTS_TEMPLATE T1 ON T.\"INGREDIENT_TYPE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Ingredient loadCurrentDeep(Cursor cursor, boolean lock) {
        Ingredient entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Meal partOfMeal = loadCurrentOther(daoSession.getMealDao(), cursor, offset);
        entity.setPartOfMeal(partOfMeal);
        offset += daoSession.getMealDao().getAllColumns().length;

        IngredientTemplate ingredientType = loadCurrentOther(daoSession.getIngredientTemplateDao(), cursor, offset);
        entity.setIngredientType(ingredientType);

        return entity;    
    }

    public Ingredient loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Ingredient> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Ingredient> list = new ArrayList<Ingredient>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Ingredient> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Ingredient> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
