package com.github.st1hy.countthemcalories.database;

import android.net.Uri;

import com.github.st1hy.countthemcalories.database.unit.AmountUnitType;

import org.greenrobot.greendao.DaoException;
import org.greenrobot.greendao.annotation.Convert;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Index;
import org.greenrobot.greendao.annotation.JoinProperty;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.ToMany;
import org.greenrobot.greendao.annotation.Unique;
import org.joda.time.DateTime;

import java.math.BigDecimal;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "INGREDIENTS_TEMPLATE".
 */
@Entity(active = true, nameInDb = "INGREDIENTS_TEMPLATE")
public class IngredientTemplate {

    @Id(autoincrement = true)
    @Unique
    @Index
    private Long id;

    @NotNull
    @Index
    private String name;

    @Convert(converter = com.github.st1hy.countthemcalories.database.property.UriPropertyConverter.class, columnType = String.class)
    private Uri imageUri;

    @Convert(converter = com.github.st1hy.countthemcalories.database.property.JodaTimePropertyConverter.class, columnType = long.class)
    @NotNull
    private DateTime creationDate;

    @Convert(converter = com.github.st1hy.countthemcalories.database.property.AmountUnitTypePropertyConverter.class, columnType = int.class)
    @NotNull
    private AmountUnitType amountType;

    @Convert(converter = com.github.st1hy.countthemcalories.database.property.BigDecimalPropertyConverter.class, columnType = String.class)
    @NotNull
    private BigDecimal energyDensityAmount;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient IngredientTemplateDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "ingredientTypeId")
    })
    private List<Ingredient> childIngredients;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "ingredientTypeId")
    })
    private List<JointIngredientTag> tags;

    @Generated
    public IngredientTemplate() {
    }

    public IngredientTemplate(Long id) {
        this.id = id;
    }

    @Generated
    public IngredientTemplate(Long id, String name, Uri imageUri, DateTime creationDate, AmountUnitType amountType, BigDecimal energyDensityAmount) {
        this.id = id;
        this.name = name;
        this.imageUri = imageUri;
        this.creationDate = creationDate;
        this.amountType = amountType;
        this.energyDensityAmount = energyDensityAmount;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getIngredientTemplateDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public Uri getImageUri() {
        return imageUri;
    }

    public void setImageUri(Uri imageUri) {
        this.imageUri = imageUri;
    }

    @NotNull
    public DateTime getCreationDate() {
        return creationDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreationDate(@NotNull DateTime creationDate) {
        this.creationDate = creationDate;
    }

    @NotNull
    public AmountUnitType getAmountType() {
        return amountType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAmountType(@NotNull AmountUnitType amountType) {
        this.amountType = amountType;
    }

    @NotNull
    public BigDecimal getEnergyDensityAmount() {
        return energyDensityAmount;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEnergyDensityAmount(@NotNull BigDecimal energyDensityAmount) {
        this.energyDensityAmount = energyDensityAmount;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Ingredient> getChildIngredients() {
        if (childIngredients == null) {
            __throwIfDetached();
            IngredientDao targetDao = daoSession.getIngredientDao();
            List<Ingredient> childIngredientsNew = targetDao._queryIngredientTemplate_ChildIngredients(id);
            synchronized (this) {
                if(childIngredients == null) {
                    childIngredients = childIngredientsNew;
                }
            }
        }
        return childIngredients;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetChildIngredients() {
        childIngredients = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<JointIngredientTag> getTags() {
        if (tags == null) {
            __throwIfDetached();
            JointIngredientTagDao targetDao = daoSession.getJointIngredientTagDao();
            List<JointIngredientTag> tagsNew = targetDao._queryIngredientTemplate_Tags(id);
            synchronized (this) {
                if(tags == null) {
                    tags = tagsNew;
                }
            }
        }
        return tags;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetTags() {
        tags = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
