package com.github.st1hy.countthemcalories.database;

import com.github.st1hy.countthemcalories.database.DaoSession;
import de.greenrobot.dao.DaoException;

import java.math.BigDecimal;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INGREDIENTS".
 */
public class Ingredient {

    private Long id;
    /** Not-null value. */
    private BigDecimal amount;
    private Long partOfMealId;
    private Long ingredientTypeId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient IngredientDao myDao;

    private Meal partOfMeal;
    private Long partOfMeal__resolvedKey;

    private IngredientTemplate ingredientType;
    private Long ingredientType__resolvedKey;


    public Ingredient() {
    }

    public Ingredient(Long id) {
        this.id = id;
    }

    public Ingredient(Long id, BigDecimal amount, Long partOfMealId, Long ingredientTypeId) {
        this.id = id;
        this.amount = amount;
        this.partOfMealId = partOfMealId;
        this.ingredientTypeId = ingredientTypeId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getIngredientDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public BigDecimal getAmount() {
        return amount;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public Long getPartOfMealId() {
        return partOfMealId;
    }

    public void setPartOfMealId(Long partOfMealId) {
        this.partOfMealId = partOfMealId;
    }

    public Long getIngredientTypeId() {
        return ingredientTypeId;
    }

    public void setIngredientTypeId(Long ingredientTypeId) {
        this.ingredientTypeId = ingredientTypeId;
    }

    /** To-one relationship, resolved on first access. */
    public Meal getPartOfMeal() {
        Long __key = this.partOfMealId;
        if (partOfMeal__resolvedKey == null || !partOfMeal__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MealDao targetDao = daoSession.getMealDao();
            Meal partOfMealNew = targetDao.load(__key);
            synchronized (this) {
                partOfMeal = partOfMealNew;
            	partOfMeal__resolvedKey = __key;
            }
        }
        return partOfMeal;
    }

    public void setPartOfMeal(Meal partOfMeal) {
        synchronized (this) {
            this.partOfMeal = partOfMeal;
            partOfMealId = partOfMeal == null ? null : partOfMeal.getId();
            partOfMeal__resolvedKey = partOfMealId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public IngredientTemplate getIngredientType() {
        Long __key = this.ingredientTypeId;
        if (ingredientType__resolvedKey == null || !ingredientType__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            IngredientTemplateDao targetDao = daoSession.getIngredientTemplateDao();
            IngredientTemplate ingredientTypeNew = targetDao.load(__key);
            synchronized (this) {
                ingredientType = ingredientTypeNew;
            	ingredientType__resolvedKey = __key;
            }
        }
        return ingredientType;
    }

    public void setIngredientType(IngredientTemplate ingredientType) {
        synchronized (this) {
            this.ingredientType = ingredientType;
            ingredientTypeId = ingredientType == null ? null : ingredientType.getId();
            ingredientType__resolvedKey = ingredientTypeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
