package com.github.st1hy.countthemcalories.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INGREDIENT_TAG_JOINTS".
*/
public class JointIngredientTagDao extends AbstractDao<JointIngredientTag, Long> {

    public static final String TABLENAME = "INGREDIENT_TAG_JOINTS";

    /**
     * Properties of entity JointIngredientTag.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TagId = new Property(1, long.class, "tagId", false, "TAG_ID");
        public final static Property IngredientTypeId = new Property(2, long.class, "ingredientTypeId", false, "INGREDIENT_TYPE_ID");
    }

    private DaoSession daoSession;

    private Query<JointIngredientTag> ingredientTemplate_TagsQuery;
    private Query<JointIngredientTag> tag_IngredientTypesQuery;

    public JointIngredientTagDao(DaoConfig config) {
        super(config);
    }
    
    public JointIngredientTagDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INGREDIENT_TAG_JOINTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"TAG_ID\" INTEGER NOT NULL ," + // 1: tagId
                "\"INGREDIENT_TYPE_ID\" INTEGER NOT NULL );"); // 2: ingredientTypeId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_INGREDIENT_TAG_JOINTS__id ON INGREDIENT_TAG_JOINTS" +
                " (\"_id\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_INGREDIENT_TAG_JOINTS_TAG_ID ON INGREDIENT_TAG_JOINTS" +
                " (\"TAG_ID\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_INGREDIENT_TAG_JOINTS_INGREDIENT_TYPE_ID ON INGREDIENT_TAG_JOINTS" +
                " (\"INGREDIENT_TYPE_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INGREDIENT_TAG_JOINTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JointIngredientTag entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTagId());
        stmt.bindLong(3, entity.getIngredientTypeId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JointIngredientTag entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTagId());
        stmt.bindLong(3, entity.getIngredientTypeId());
    }

    @Override
    protected final void attachEntity(JointIngredientTag entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JointIngredientTag readEntity(Cursor cursor, int offset) {
        JointIngredientTag entity = new JointIngredientTag( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // tagId
            cursor.getLong(offset + 2) // ingredientTypeId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JointIngredientTag entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTagId(cursor.getLong(offset + 1));
        entity.setIngredientTypeId(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JointIngredientTag entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JointIngredientTag entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JointIngredientTag entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "tags" to-many relationship of IngredientTemplate. */
    public List<JointIngredientTag> _queryIngredientTemplate_Tags(long ingredientTypeId) {
        synchronized (this) {
            if (ingredientTemplate_TagsQuery == null) {
                QueryBuilder<JointIngredientTag> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IngredientTypeId.eq(null));
                ingredientTemplate_TagsQuery = queryBuilder.build();
            }
        }
        Query<JointIngredientTag> query = ingredientTemplate_TagsQuery.forCurrentThread();
        query.setParameter(0, ingredientTypeId);
        return query.list();
    }

    /** Internal query to resolve the "ingredientTypes" to-many relationship of Tag. */
    public List<JointIngredientTag> _queryTag_IngredientTypes(long tagId) {
        synchronized (this) {
            if (tag_IngredientTypesQuery == null) {
                QueryBuilder<JointIngredientTag> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TagId.eq(null));
                tag_IngredientTypesQuery = queryBuilder.build();
            }
        }
        Query<JointIngredientTag> query = tag_IngredientTypesQuery.forCurrentThread();
        query.setParameter(0, tagId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTagDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getIngredientTemplateDao().getAllColumns());
            builder.append(" FROM INGREDIENT_TAG_JOINTS T");
            builder.append(" LEFT JOIN TAGS T0 ON T.\"TAG_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN INGREDIENTS_TEMPLATE T1 ON T.\"INGREDIENT_TYPE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected JointIngredientTag loadCurrentDeep(Cursor cursor, boolean lock) {
        JointIngredientTag entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Tag tag = loadCurrentOther(daoSession.getTagDao(), cursor, offset);
         if(tag != null) {
            entity.setTag(tag);
        }
        offset += daoSession.getTagDao().getAllColumns().length;

        IngredientTemplate ingredientType = loadCurrentOther(daoSession.getIngredientTemplateDao(), cursor, offset);
         if(ingredientType != null) {
            entity.setIngredientType(ingredientType);
        }

        return entity;    
    }

    public JointIngredientTag loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<JointIngredientTag> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<JointIngredientTag> list = new ArrayList<JointIngredientTag>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<JointIngredientTag> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<JointIngredientTag> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
