package com.github.st1hy.countthemcalories.database;

import com.github.st1hy.countthemcalories.database.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INGREDIENT_TAG_JOINTS".
 */
public class JointIngredientTag {

    private Long id;
    private long tagId;
    private long ingredientTypeId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient JointIngredientTagDao myDao;

    private Tag tag;
    private Long tag__resolvedKey;

    private IngredientTemplate ingredientType;
    private Long ingredientType__resolvedKey;


    public JointIngredientTag() {
    }

    public JointIngredientTag(Long id) {
        this.id = id;
    }

    public JointIngredientTag(Long id, long tagId, long ingredientTypeId) {
        this.id = id;
        this.tagId = tagId;
        this.ingredientTypeId = ingredientTypeId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getJointIngredientTagDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTagId() {
        return tagId;
    }

    public void setTagId(long tagId) {
        this.tagId = tagId;
    }

    public long getIngredientTypeId() {
        return ingredientTypeId;
    }

    public void setIngredientTypeId(long ingredientTypeId) {
        this.ingredientTypeId = ingredientTypeId;
    }

    /** To-one relationship, resolved on first access. */
    public Tag getTag() {
        long __key = this.tagId;
        if (tag__resolvedKey == null || !tag__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TagDao targetDao = daoSession.getTagDao();
            Tag tagNew = targetDao.load(__key);
            synchronized (this) {
                tag = tagNew;
            	tag__resolvedKey = __key;
            }
        }
        return tag;
    }

    public void setTag(Tag tag) {
        if (tag == null) {
            throw new DaoException("To-one property 'tagId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.tag = tag;
            tagId = tag.getId();
            tag__resolvedKey = tagId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public IngredientTemplate getIngredientType() {
        long __key = this.ingredientTypeId;
        if (ingredientType__resolvedKey == null || !ingredientType__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            IngredientTemplateDao targetDao = daoSession.getIngredientTemplateDao();
            IngredientTemplate ingredientTypeNew = targetDao.load(__key);
            synchronized (this) {
                ingredientType = ingredientTypeNew;
            	ingredientType__resolvedKey = __key;
            }
        }
        return ingredientType;
    }

    public void setIngredientType(IngredientTemplate ingredientType) {
        if (ingredientType == null) {
            throw new DaoException("To-one property 'ingredientTypeId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.ingredientType = ingredientType;
            ingredientTypeId = ingredientType.getId();
            ingredientType__resolvedKey = ingredientTypeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
