package com.github.st1hy.countthemcalories.database;

import org.greenrobot.greendao.annotation.*;

import com.github.st1hy.countthemcalories.database.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "INGREDIENT_TAG_JOINTS".
 */
@Entity(active = true, nameInDb = "INGREDIENT_TAG_JOINTS")
public class JointIngredientTag {

    @Id(autoincrement = true)
    @Unique
    @Index
    private Long id;

    @Index
    private long tagId;

    @Index
    private long ingredientTypeId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient JointIngredientTagDao myDao;

    @ToOne(joinProperty = "tagId")
    private Tag tag;

    @Generated
    private transient Long tag__resolvedKey;

    @ToOne(joinProperty = "ingredientTypeId")
    private IngredientTemplate ingredientType;

    @Generated
    private transient Long ingredientType__resolvedKey;

    @Generated
    public JointIngredientTag() {
    }

    public JointIngredientTag(Long id) {
        this.id = id;
    }

    @Generated
    public JointIngredientTag(Long id, long tagId, long ingredientTypeId) {
        this.id = id;
        this.tagId = tagId;
        this.ingredientTypeId = ingredientTypeId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getJointIngredientTagDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTagId() {
        return tagId;
    }

    public void setTagId(long tagId) {
        this.tagId = tagId;
    }

    public long getIngredientTypeId() {
        return ingredientTypeId;
    }

    public void setIngredientTypeId(long ingredientTypeId) {
        this.ingredientTypeId = ingredientTypeId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Tag getTag() {
        long __key = this.tagId;
        if (tag__resolvedKey == null || !tag__resolvedKey.equals(__key)) {
            __throwIfDetached();
            TagDao targetDao = daoSession.getTagDao();
            Tag tagNew = targetDao.load(__key);
            synchronized (this) {
                tag = tagNew;
            	tag__resolvedKey = __key;
            }
        }
        return tag;
    }

    @Generated
    public void setTag(Tag tag) {
        if (tag == null) {
            throw new DaoException("To-one property 'tagId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.tag = tag;
            tagId = tag.getId();
            tag__resolvedKey = tagId;
        }
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public IngredientTemplate getIngredientType() {
        long __key = this.ingredientTypeId;
        if (ingredientType__resolvedKey == null || !ingredientType__resolvedKey.equals(__key)) {
            __throwIfDetached();
            IngredientTemplateDao targetDao = daoSession.getIngredientTemplateDao();
            IngredientTemplate ingredientTypeNew = targetDao.load(__key);
            synchronized (this) {
                ingredientType = ingredientTypeNew;
            	ingredientType__resolvedKey = __key;
            }
        }
        return ingredientType;
    }

    @Generated
    public void setIngredientType(IngredientTemplate ingredientType) {
        if (ingredientType == null) {
            throw new DaoException("To-one property 'ingredientTypeId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.ingredientType = ingredientType;
            ingredientTypeId = ingredientType.getId();
            ingredientType__resolvedKey = ingredientTypeId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
