package com.github.st1hy.countthemcalories.database;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.github.st1hy.countthemcalories.database.DaoSession;
import org.greenrobot.greendao.DaoException;

import android.net.Uri;
import org.joda.time.DateTime;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MEALS".
 */
@Entity(active = true, nameInDb = "MEALS")
public class Meal {

    @Id(autoincrement = true)
    @Unique
    @Index
    private Long id;

    @Index
    private String name;

    @Convert(converter = com.github.st1hy.countthemcalories.database.property.UriPropertyConverter.class, columnType = String.class)
    private Uri imageUri;

    @Convert(converter = com.github.st1hy.countthemcalories.database.property.JodaTimePropertyConverter.class, columnType = long.class)
    @NotNull
    private DateTime creationDate;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient MealDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "partOfMealId")
    })
    private List<Ingredient> ingredients;

    @Generated
    public Meal() {
    }

    public Meal(Long id) {
        this.id = id;
    }

    @Generated
    public Meal(Long id, String name, Uri imageUri, DateTime creationDate) {
        this.id = id;
        this.name = name;
        this.imageUri = imageUri;
        this.creationDate = creationDate;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMealDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Uri getImageUri() {
        return imageUri;
    }

    public void setImageUri(Uri imageUri) {
        this.imageUri = imageUri;
    }

    @NotNull
    public DateTime getCreationDate() {
        return creationDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreationDate(@NotNull DateTime creationDate) {
        this.creationDate = creationDate;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Ingredient> getIngredients() {
        if (ingredients == null) {
            __throwIfDetached();
            IngredientDao targetDao = daoSession.getIngredientDao();
            List<Ingredient> ingredientsNew = targetDao._queryMeal_Ingredients(id);
            synchronized (this) {
                if(ingredients == null) {
                    ingredients = ingredientsNew;
                }
            }
        }
        return ingredients;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetIngredients() {
        ingredients = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
